# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black

# - repo: https://github.com/python-poetry/poetry
#   rev: 1.4.0
#   hooks:
#     - id: poetry-check
#     - id: poetry-export
#       args: ["-f", "requirements.txt", "-o", "requirements.txt"]
