name: push-workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install pylint
      - name: Run pylint
        continue-on-error: true
        run: |
          pylint --output-format=parseable *.py > LintReport.txt
      - name: Upload LintReport.txt
        uses: actions/upload-artifact@v3
        with:
          name: LintReport
          path: LintReport.txt